name: Build
description: build multi versions
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        name: Artifacts
        path: gathered-artifacts

    - name: Make build summary
      run: python3 .github/workflows/scripts/summary.py  # ubuntu-22.04 uses Python 3.10.6
      shell: bash
      env:
        TARGET_SUBPROJECT: '' # leaving this empty means all subprojects
