name: Build
description: build multi versions
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Build with gradle
      shell: bash
      run: |
        chmod +x gradlew
        echo "Building..."
        ./gradlew build
      env:
        BUILD_ID: ${{ github.run_number }}
        BUILD_RELEASE: false

    - name: Gather artifacts
      shell: bash
      run: |
        mkdir gathered-artifacts
        cp -r versions/*/build/libs/* gathered-artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: gathered-artifacts